spring:
  datasource:
    druid:
    url: jdbc:mysql://121.4.154.210/pineapplestore?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: linson
    password: 19990213
    driver-class-name: com.mysql.cj.jdbc.Driver

    redis:
      host: 127.0.0.1
      port: 6379




mybatis-plus:
  mapper-locations: classpath*:mappers/*Mapper.xml
  type-aliases-package: com.PineappleStore.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

